package edu.tamu.spinnstone.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import edu.tamu.spinnstone.models.MenuItem;
import edu.tamu.spinnstone.models.sql.Database;
import rx.subjects.PublishSubject;

import javax.swing.*;
import javax.swing.event.TableModelEvent;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashMap;

public class ManagerDashboard {
    private JTable MenuItemsTable;
    private JPanel container;
    private JScrollPane DashboardTableContainer;

    public ManagerDashboard() {
        $$$setupUI$$$();
        populateMenuItemsTable();
    }



    private void populateMenuItemsTable() {
        Database database = Actions.getDatabase.getValue();
        MenuItem menu_item = new MenuItem(database);
        ArrayList<String[]> dataToDisplay = new ArrayList<>();

        try {
            ResultSet product_data = menu_item.getView();
            do {
                String[] dataRow = new String[2];

                dataRow[0] = product_data.getString("item_name");
                dataRow[1] = product_data.getString("menu_item_price");

                dataToDisplay.add(dataRow);

            } while (product_data.next());
        } catch (SQLException e) {
            System.out.println("SQL exception: " + e);
        }

        // Initializing the JTable
        String[] columnNames = {"Menu Item", "Price"};
        String[][] dataToDisplayArray = dataToDisplay.toArray(new String[dataToDisplay.size()][]);
        Integer[] editableCols = {1};

        PublishSubject<TableModelEvent> changeListener = PublishSubject.create();

        DataTable dataTable = new DataTable(dataToDisplayArray, columnNames, editableCols, changeListener);

        changeListener.subscribe(event -> {
            Database db = Actions.getDatabase.getValue();
            String value = dataTable.getValueAt(event.getFirstRow(), event.getColumn()).toString();
            String itemName = dataTable.getValueAt(event.getFirstRow(), 0).toString();
            try {
                db.update(MenuItem.TableName).set(
                        new HashMap<String, Object>() {{
                            put(
                                    MenuItem.ColumnNames.MENU_ITEM_PRICE.toString(),
                                    new BigDecimal(value.substring(1))

                            );
                        }}
                ).where(MenuItem.ColumnNames.ITEM_NAME.toString(), itemName).execute();
            } catch (Exception e) {
                System.out.println(e);
            }
        });

        MenuItemsTable = new JTable(dataTable);

        DashboardTableContainer.setViewportView(MenuItemsTable);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        container = new JPanel();
        container.setLayout(new GridLayoutManager(1, 1, new Insets(8, 8, 8, 8), -1, -1));
        DashboardTableContainer = new JScrollPane();
        container.add(DashboardTableContainer, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        MenuItemsTable = new JTable();
        DashboardTableContainer.setViewportView(MenuItemsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return container;
    }

}
