package edu.tamu.spinnstone.ui;

import edu.tamu.spinnstone.models.Order;
import edu.tamu.spinnstone.models.sql.Database;
import edu.tamu.spinnstone.ui.screens.ManagerView;
import edu.tamu.spinnstone.ui.screens.ServerScreen;

import javax.swing.*;
import java.awt.*;

public class ScreenManager {

    public ScreenManager(Database db) {
        Order order = new Order(db);

        Actions.getOrder.onNext(order);
        Actions.setViewCard.subscribe(cardName -> ((CardLayout) manageContainer.getLayout()).show(manageContainer, cardName.toString()));
    }

    public JPanel manageContainer;
    private ManagerView ManagerButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        manageContainer = new JPanel();
        manageContainer.setLayout(new CardLayout(0, 0));
        final ServerScreen nestedForm1 = new ServerScreen();
        manageContainer.add(nestedForm1.$$$getRootComponent$$$(), "ServerCard");
        ManagerButton = new ManagerView();
        manageContainer.add(ManagerButton.$$$getRootComponent$$$(), "ManagerCard");
    }

    public JComponent $$$getRootComponent$$$() {
        return manageContainer;
    }

}
